### ISSUE TITLE
Add a rubocop config file

### ISSUE THREAD

**Issue by Tech356** [xanzy/chef-guard-cookbook#21]
Tuning rubocop to a specific style is always needed. This cookbook should place a `.rubocop.yml` file in the configured tempdir so that rubocop finds it when checking uploaded cookbooks.  

Another option would be configuring Chef-Guard to invoke rubocop with the `--config` option.

**Comment by iroller** [comment]
:+1:

**Comment by svanharmelen** [comment]
A global `.rubocop.yml` could only work together with the `.rubocop.yml` of the cookbook that is being uploaded if that `.rubocop.yml` contains a `inherit_from:` section. But doing that wouldn't make sense for the cookbook maintainer as most likely not everyone is using Chef-Guard (maybe one day :wink:).

So in the end I think that the cookbook being uploaded should contain everything needed to pass the checks.

The only other way would be to have Chef-Guard read and alter (merge) the `.rubobop.yml` file found (if any) in the cookbook being uploaded with one provided centrally to Chef-Guard. But I don't think I like that approach much...

**Comment by svanharmelen** [comment]
Closing this as this will not be added to this cookbook. A cookbook should have it's own correct `.rubocop.yml` as that is the only location where all the details of that specific cookbook are known.
